/*
    Generated by Atomist on 19 07 2016 
*/
package org.acolyer.atomist.rest;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class AtomistRestApplication {

    public static void main(String[] args) {
        SpringApplication.run(AtomistRestApplication.class, args);
    }
}
