/*
    Generated by Atomist on 19 07 2016 
*/
package org.acolyer.atomist.rest;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
* Spring Java configuration file for AtomistRest.
* Don't even think of using XML.
*/
@Configuration
public class AtomistRestConfiguration {

    // Your beans go here ... 
	// Atomist Bot suggests "maybe use an Atomist project editor to add a sample one?"
}
