/*
    Generated by Atomist on 19 07 2016 
*/
package org.acolyer.atomist.rest;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.test.context.web.WebAppConfiguration;
import org.springframework.boot.test.SpringApplicationConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

@RunWith(SpringJUnit4ClassRunner.class)
@SpringApplicationConfiguration(classes = AtomistRestApplication.class)
@WebAppConfiguration
public class AtomistRestApplicationTests {

	@Test
	public void contextLoads() {
	}
}
